[workspace]

members = [
	"cryptography-core",
	"mercat",
	"mercat/cli/account",
	"mercat/cli/chain_setup",
	"mercat/cli/common",
	"mercat/cli/mediator",
	"mercat/cli/validator",
	"mercat/cli/interactive",
	"mercat/wasm",
	"confidential-identity",
	"confidential-identity/ffi",
	"confidential-identity/cli/scp",
	"confidential-identity/cli/scv",
	"confidential-identity/wasm",
	"private-identity-audit",
	"private-identity-audit/ffi",
	"private-identity-audit/wasm",
]
