[package]
name = "polymath-scv"
version = "1.0.0"
authors = [ "Polymath Inc" ]
repository = "https://github.com/PolymathNetwork/cryptography"
description = "Confidential Identity Library: Simple Claim Verifier"
edition = "2018"

[dependencies]
cli_common = { package = "confidential_identity_cli_common", path = "../common/" }
confidential_identity = { path = "../.." }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# Crypto
schnorrkel = { version = "0.10", default-features = false }
curve25519-dalek = { version = "3.2", default-features = false, features = ["nightly", "alloc"] }

# Only binaries
structopt = { version = "0.3", default-features = false }
