[package]
name = "polymath-scp"
version = "1.0.0"
authors = [ "Polymath Inc" ]
repository = "https://github.com/PolymathNetwork/cryptography"
description = "Confidential Identity Library: Simple Claim Prover"
edition = "2018"

[dependencies]
cli_common = { package = "confidential_identity_cli_common", path = "../common/" }
confidential_identity = { path = "../../" }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# Crypto
rand = { version = "0.7.3", features = ["wasm-bindgen", "getrandom", "alloc"], default-features = false }
rand_core = { version = "0.5", default-features = false}
curve25519-dalek = { git = "https://github.com/PolymathNetwork/curve25519-dalek.git", branch = "v2-packed-simd", default-features = false, features = ["nightly", "u64_backend"] }

# Only binaries
structopt = { version = "0.3", default-features = false }
